#^ 10. MVC

# MVC (model-view-controller) is a design pattern
# that divides the responsibilities of an app
# between models, views and controllers. Rails
# follows this pattern by convention.

# Models are responsible for data management, they
# talk with the database and hold some business
# logic.
# Views are responsible for data presentation,
# in case of a web app, they are html templates
# that say how the data will be displated to
# the user who requested it.
# Controllers are responsible for taking the input
# from the request, and then using it and models
# to retrieve the correct data, pass it on to the
# view, and then send back the page generated by the
# view to the user.

# We already have a model with a few records in
# the database, and we know how to create controllers
# and views, so let's put it all together.

#~ exercise:
# - create a page at /posts that will list all
#   posts currently in the db
# - each post should be displayed as a card
#   with title at the top and body below it
# - hint: instance variables created in controller
#         actions are available in views
